### ISSUE TITLE
Torsion scan failing

### ISSUE THREAD

**Issue by gwenwhite** [qubekit/QUBEKit#305]
Hello, I am trying to run a molecule in QUBEKit but it keeps failing on the torsion_scanner step. The molecule is a fragment of a bigger molecule. For reference, I have attached a copy of the .sdf file I am using,  the QUBEKit.err file that is being outputted, and an image outlining the fragment of the molecule I am using. 

[y6-fring5.sdf.txt](https://github.com/qubekit/QUBEKit/files/8508285/y6-fring5.sdf.txt)
[QUBEKit.err.txt](https://github.com/qubekit/QUBEKit/files/8508287/QUBEKit.err.txt)
[y6-endgroup.pdf](https://github.com/qubekit/QUBEKit/files/8508309/y6-endgroup.pdf)

**Comment by jthorton** [comment]
Hi, @gwenwhite thanks for opening the issue and attaching all of the relevant files this was very helpful. I think the issue is the input SDF file, the file implies single bonds between all atoms which is not correct and we use smarts queries to identify rotatable bonds which will be scanned and refit in this case the linear triple bonds are scanned due to the incorrect bond orders. For this molecule, it's probably safe to skip the torsion scan stage as there is only one rotatable bond in the fragment and it's a double bond, to make qubekit end at this stage go to the folder made during the qubekit run and use the following command `qubekit restart bonded_parameters -e bonded_parameters` this will make qubekit write the final parameters to file with no refit torsions. Otherwise, you will need to start the run again with a new SDF file with the correct bond orders.

**Comment by gwenwhite** [comment]
This was very helpful. Thank you!
