### ISSUE TITLE
Conflict between QUBEKit and psi4 in conda

### ISSUE THREAD

**Issue by qyuan71** [qubekit/QUBEKit#367]
Hi all,

I tried to install QUBEKit and the dependencies via conda, however, after installing QUBEKit using conda, I can't install psi4 into the same environment - there were many conflicts reported by conda. The same error occurred when I installed psi4 first and tried to install QUBEKit - I used the same conda commands as suggested in the README file. I built the conda envs using Python 3.9 

Any suggestions that can help make QUBEKit and psi4 work in the same conda environment? A related question is that is it possible to use QUBEKit to generate input files for psi4 and read the results back to QUBEKit again to avoid using them in the same environment, if so, how can I do it?

Thanks very much!

Qi

**Comment by bieniekmateusz** [comment]
Hi Qi. 

We are still waiting for psi4 to become available on conda-forge. There is a clash between conda-forge and the psi4 channels. We reverted to mamba (conda-extension) in order to resolve the conflicts between the packages. I'd recommend trying mamba with our build environment available under `devtools/conda-envs/everything.yaml` first. 

Alternatively, after installing qubekit, you can add your own local psi4 to the PATH (this could cause issues and depends on how it was compiled) or to simply compile psi4.

**Comment by jthorton** [comment]
Reminder add this to readme/docs for other users.
